apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  resources:
    requests:
      storage: 5Gi # request 5Gi storage
  accessModes:
    - ReadWriteOnce # only allow one node can be read and write
  storageClassName: "manual"