apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis # label selectors Pod redis
  type: ClusterIP
  ports:
    - port: 6379 # port of the serivce
      targetPort: 6379 # port of the container that service will forward to 